=== sonost/Distributed-Programming-Assignments/Assignment1/dtd/nffgInfo.dtd
<!ELEMENT nffgService (nffgs)>
<!ELEMENT nffgs (nffg+)>
<!ELEMENT nffg (nodes,links,policies)>
<!ELEMENT nodes (node+)>
<!ELEMENT node (funcType)>
<!ELEMENT links (link+)>
<!ELEMENT link EMPTY>
<!ELEMENT policies (policy+)>
<!ELEMENT policy (reachabilityPolicy|traversalPolicy)>
<!ELEMENT reachabilityPolicy (verificationResult?)>
<!ELEMENT traversalPolicy (funcType+,verificationResult?)>
<!ELEMENT funcType EMPTY>
<!ELEMENT verificationResult EMPTY>


<!ATTLIST nffg 
	nffgName 	ID 		#REQUIRED
	updateTime CDATA 	#REQUIRED>
<!ATTLIST node
	nodeName 	  		ID 		#REQUIRED>
<!ATTLIST link
	linkName 	ID 	#REQUIRED
	sourceNode 	IDREF 	#REQUIRED
	destNode 	IDREF   #REQUIRED>
<!ATTLIST policy 
	policyName    		ID 				#REQUIRED>
<!ATTLIST reachabilityPolicy 
	relatedNffgName    IDREF			#REQUIRED
	sourceNode 	IDREF 	#REQUIRED
	destNode 	IDREF   #REQUIRED
	isPositive	(true|false)			#REQUIRED>
<!ATTLIST traversalPolicy 
	relatedNffgName    IDREF			#REQUIRED
	sourceNode 	IDREF 	#REQUIRED
	destNode 	IDREF   #REQUIRED
	isPositive	(true|false)			#REQUIRED>
 <!ATTLIST funcType 
	nodeType (CACHE|DPI|FW|MAIL_CLIENT|MAIL_SERVER|NAT|SPAM|VPN|WEB_CLIENT|WEB_SERVER)	#REQUIRED>
<!ATTLIST verificationResult 
	result 					(true|false)		#REQUIRED
	message 				CDATA  		 #IMPLIED
	verificationTime 		CDATA 			#IMPLIED>

=== sonost/Distributed-Programming-Assignments/Assignment1/dtd/nffgInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nffgService SYSTEM "nffgInfo.dtd">
<nffgService>
	<nffgs>
		<nffg nffgName="nffg1" updateTime="2015-10-15T11:32:40.000+02:00">
			<nodes>
				<node nodeName="firewall1">
					<funcType nodeType = "FW"/>
				</node>
				
				<node nodeName="webServer1">
					<funcType nodeType = "NAT"/>
				</node>
			</nodes>
			
			<links>
				<link linkName="l12" sourceNode="firewall1" destNode="webServer1"></link>
			</links>
			
			<policies>
				<policy policyName="policy4" >
					<reachabilityPolicy relatedNffgName="nffg1" sourceNode="firewall1" destNode="webServer1"  isPositive="true">
						<verificationResult result="true" message="policy result is true" verificationTime="2015-02-15T11:32:40.000+02:00"/>
					</reachabilityPolicy>
				</policy>
			</policies>
		</nffg>
		
	</nffgs>
</nffgService>
