=== sonost/Distributed-Programming-Assignments/Assignment1/xsd/nffgInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/nffgInfo"
xmlns:tns="http://www.example.org/nffgInfo" elementFormDefault="qualified">

<element name="nffgService" type="tns:nffgServiceType">

	<key name="nffgNameKey">
		<selector xpath="tns:nffg" />
		<field xpath="@nffgName" />
	</key>
	
	<keyref name="nffgNameKeyRef" refer="tns:nffgNameKey">
      <selector xpath="tns:nffg"></selector>
      <field xpath="@relatedNffgName"></field>
    </keyref>
    
    <key name="policyNameKey">
		<selector xpath="tns:nffg/tns:policies/tns:policy" />
		<field xpath="@policyName" />
	</key>
	
</element>
	

<complexType name="nffgServiceType">
    	<sequence>
    		<element name="nffg" minOccurs="0" maxOccurs="unbounded" type="tns:nffgType">
    			<key name="nodeNameKey">
					<selector xpath="tns:nodes/tns:node" />
			   		<field xpath="@nodeName" />
				</key>
				
				<keyref name="nodeNameKeyRef" refer="tns:nodeNameKey">
      				<selector xpath="tns:nodes/tns:node"></selector>
      				<field xpath="@nodeName"></field>
    			</keyref>
				
				<key name="linkNameKey">
    				<selector xpath="tns:links/tns:link" />
    				<field xpath="@linkName" />
    			</key>
    		</element>
    	</sequence>
</complexType>

<complexType name="nffgType">
    <sequence>
		<element name="nodes" type="tns:nodesType"></element>
  		<element name="links" type="tns:linksType"></element>
 		<element name="policies" minOccurs="1" maxOccurs="1" type="tns:policiesType"></element>
    </sequence>
    <attribute name="nffgName" use="required" type="tns:nameType"></attribute>
    <attribute name="updateTime" use="required" type="dateTime"></attribute>
</complexType>


<complexType name="nodesType">
    <sequence>
    	<element name="node" minOccurs="1" maxOccurs="unbounded" type="tns:nodeType"></element>
    </sequence>
</complexType>


<complexType name="nodeType">
    <sequence>
		<element name="fType" type="tns:fType"></element>
    </sequence>
    <attribute name="nodeName" use="required" type="tns:nameType"/>
</complexType> 

<complexType name="linksType">
   	<sequence>
   		<element name="link" minOccurs="1" maxOccurs="unbounded" type="tns:linkType"></element>
   	</sequence>
</complexType>

<complexType name="linkType">
    <sequence>
    	<element name="sourceNode"  type="tns:nameType"></element>
    	<element name="destNode"  type="tns:nameType"></element>
    </sequence>
    <attribute name="linkName" use="required" type="tns:nameType"/>
</complexType>


<simpleType name="nameType">
	<restriction base="token">
	   	<minLength value="1"></minLength>
    	<pattern value="[A-Za-z][A-Za-z0-9]*"/>
	</restriction>
</simpleType>


<complexType name="fType">
	<sequence>
		<element name="funcType" type="tns:funcType" minOccurs="1" maxOccurs="1" />
	</sequence>
</complexType>


<complexType name="policiesType">
  	<sequence>
    	<element name="reachabilityPolicy" minOccurs="0" maxOccurs="unbounded" type="tns:reachPolType" ></element> 
    	<element name="traversalPolicy" minOccurs="0" maxOccurs="unbounded"  type="tns:travPolType" ></element>
   	</sequence>
</complexType>


<complexType name="reachPolType">
	<sequence>
		<element name="verificationResult"  minOccurs="0"  type="tns:verifResType"></element>
		<element name="sourceNode"  type="tns:nameType"></element>
    	<element name="destNode"  type="tns:nameType"></element>
    </sequence>
    <attribute name="policyName" use="required" type="tns:nameType"/>
    <attribute name="relatedNffgName" use="required" type="tns:nameType"/>
    <attribute name="isPositive" use="required" type="boolean"/>
</complexType>


<complexType name="travPolType">
	<complexContent>
		<extension base="tns:reachPolType">
				<sequence>
					<element name="traversedFunc" type="tns:funcType" maxOccurs="unbounded"></element>
				</sequence>
		</extension>
	</complexContent>
</complexType>


<complexType name="verifResType">
	<sequence>
    	<element name="result" minOccurs="0" type="boolean"></element>
    	<element name="verificationTime" minOccurs="0" type="dateTime"></element>
    	<element name="message" minOccurs="0" type="string"></element>
    </sequence>
</complexType>


<simpleType name="funcType">
		<restriction base="string">
    		<enumeration value="CACHE"></enumeration>
   			<enumeration value="DPI"></enumeration>
    		<enumeration value="FW"></enumeration>
   			<enumeration value="MAIL_CLIENT"></enumeration>
   			<enumeration value="MAIL_SERVER"></enumeration>
			<enumeration value="NAT"></enumeration>
   			<enumeration value="SPAM"></enumeration>
			<enumeration value="VPN"></enumeration>
			<enumeration value="WEB_CLIENT"></enumeration>
			<enumeration value="WEB_SERVER"></enumeration>
		</restriction>
</simpleType>

</schema>

=== sonost/Distributed-Programming-Assignments/Assignment1/xsd/nffgInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE xml>
<nffgService xmlns="http://www.example.org/nffgInfo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/1aa nffgInfo.xsd">
        <nffg nffgName="nffg1" updateTime="2015-11-15T11:32:40.000+02:00">
			<nodes>
				<node nodeName="firewall1">
					<fType>
						<funcType>FW</funcType>
					</fType>
				</node>
				
				<node nodeName="firewall2">
					<fType>
						<funcType>FW</funcType>
					</fType>
				</node>
				
				<node nodeName="webServer1">
					<fType>
						<funcType>WEB_SERVER</funcType>
					</fType>
				</node>
				
				<node nodeName="mailServer1">
					<fType>
						<funcType>MAIL_SERVER"</funcType>
					</fType>
				</node>
			</nodes>
		</nffg>
		
		<nffg nffgName="nffg2">
			<nodes>
				<node nodeName="mailServer1">
					<fType>
						<funcType>MAIL_SERVER</funcType>
					</fType>
				</node>
				
				<node nodeName="NAT1">
					<fType>
						<funcType>NAT</funcType>
					</fType>
				</node>
				
				<node nodeName="firewall1">
					<fType>
						<funcType>FW</funcType>
					</fType>
				</node>
				
				<node nodeName="webServer2">
					<fType>
						<funcType>WEB_SERVER</funcType>
					</fType>
				</node>
			</nodes>
			
			<links>
				<link linkName="l12">
               		<sourceNode>firewall1</sourceNode>
                	<destNode>firewall2</destNode>
           		</link>
           		
           		<link linkName="l13">
               		<sourceNode>firewall1</sourceNode>
                	<destNode>webServer1</destNode>
           		</link>
           		
           		<link linkName="l21">
               		<sourceNode>firewall2</sourceNode>
                	<destNode>firewall1</destNode>
           		</link>
           		
                <link linkName="l23">
               		<sourceNode>firewall2</sourceNode>
                	<destNode>NAT1</destNode>
           		</link>
           		
                <link linkName="l13">
               		<sourceNode>webServer1</sourceNode>
                	<destNode>webServer1</destNode>
           		</link>
			</links>
			
			
			<policies>
				
				<reachabilityPolicy policyName="policy1" relatedNffg="nffg0" isPositive="true">
	            	<sourceNode>webServer1</sourceNode>
                	<destNode>NAT1</destNode>
                	<verificationResult>
                		<result>true</result>
                    	<verificationTime>2015-11-15T11:32:40.000+02:00</verificationTime>
                   		<message>the result of policy verification is true</message>
               		</verificationResult>
				</reachabilityPolicy>
				
				<reachabilityPolicy policyName="policy2" relatedNffg="nffg0" isPositive="true">
	            	<sourceNode>mailServer1</sourceNode>
                	<destNode>webServer2</destNode>
                	<verificationResult>
                		<result>true</result>
                    	<verificationTime>2015-11-15T11:32:40.000+02:00</verificationTime>
                   		<message>the result of policy verification is true</message>
               		</verificationResult>
				</reachabilityPolicy>
		
				<traversalPolicy policyName="policy2" relatedNffg="nffg0" isPositive="true">
	            	<sourceNode>mailServer1</sourceNode>
                	<destNode>webServer2</destNode>
                	<verificationResult>
                		<result>true</result>
                    	<verificationTime>2015-11-15T11:32:40.000+02:00</verificationTime>
                   		<message>the result of policy verification is true</message>
               		</verificationResult>
                	<traversedFunc>NAT</traversedFunc>
            	</traversalPolicy>
            	
            	<traversalPolicy policyName="policy1" relatedNffg="nffg0" isPositive="true">
	            	<sourceNode>mailServer2</sourceNode>
                	<destNode>webClient1</destNode>
                	<verificationResult>
                		<result>true</result>
                    	<verificationTime>2015-11-15T11:32:40.000+02:00</verificationTime>
                   		<message>the result of policy verification is true</message>
               		</verificationResult>
                	<traversedFunc>NAT</traversedFunc>
                	<traversedFunc>FW</traversedFunc>
                	<traversedFunc>DPI</traversedFunc>
            	</traversalPolicy>
            	
			</policies>
	
		</nffg>

</nffgService>
